name: workout_program
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_database: ^10.2.4
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_auth: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/FitEquipLogo.png
      - assets/Rectangle.png

      # EQUIPMENT ICONS:
      # ab roller by Md Moniruzzaman from <a href="https://thenounproject.com/browse/icons/term/ab-roller/" target="_blank" title="ab roller Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/abRoller.png
      # dumbells by Rama Lemon from <a href="https://thenounproject.com/browse/icons/term/dumbells/" target="_blank" title="dumbells Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/dumbbells.png
      # lat pulldown by Nawicon from <a href="https://thenounproject.com/browse/icons/term/lat-pulldown/" target="_blank" title="lat pulldown Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/latPulldown.png
      # Kettlebells by She3t, llc from <a href="https://thenounproject.com/browse/icons/term/kettlebells/" target="_blank" title="Kettlebells Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/kettlebells.png
      # skipping rope by Handicon from <a href="https://thenounproject.com/browse/icons/term/skipping-rope/" target="_blank" title="skipping rope Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/jumprope.png
      # Barbell by Alena Artemova from <a href="https://thenounproject.com/browse/icons/term/barbell/" target="_blank" title="Barbell Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/barbell.png
      # squat rack by Fahrul Oktaviana from <a href="https://thenounproject.com/browse/icons/term/squat-rack/" target="_blank" title="squat rack Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/squatRack.png
      # adjustable exercise bench by Oleksandr Panasovskyi from <a href="https://thenounproject.com/browse/icons/term/adjustable-exercise-bench/" target="_blank" title="adjustable exercise bench Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/flatBench.png
      # Weight bench by Agan24 from <a href="https://thenounproject.com/browse/icons/term/weight-bench/" target="_blank" title="Weight bench Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/inclineBench.png
      # chest fly machine by Juicy Fish from <a href="https://thenounproject.com/browse/icons/term/chest-fly-machine/" target="_blank" title="chest fly machine Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/pecDeckMachine.png
      # Leg Extension by firda ardiansyah from <a href="https://thenounproject.com/browse/icons/term/leg-extension/" target="_blank" title="Leg Extension Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/legExtension.png
      # stepper machine by Juicy Fish from <a href="https://thenounproject.com/browse/icons/term/stepper-machine/" target="_blank" title="stepper machine Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/stairmaster.png
      # running machine by Juicy Fish from <a href="https://thenounproject.com/browse/icons/term/running-machine/" target="_blank" title="running machine Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/treadmill.png
      # stationary bike by iconixar from <a href="https://thenounproject.com/browse/icons/term/stationary-bike/" target="_blank" title="stationary bike Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/stationaryBike.png
      # Rowing Machine by Grégory Montigny from <a href="https://thenounproject.com/browse/icons/term/rowing-machine/" target="_blank" title="Rowing Machine Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/rowingMachine.png
      # Pull Up Bar by Grégory Montigny from <a href="https://thenounproject.com/browse/icons/term/pull-up-bar/" target="_blank" title="Pull Up Bar Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/pullUpBar.png
      # cable pulling by Smashing Stocks from <a href="https://thenounproject.com/browse/icons/term/cable-pulling/" target="_blank" title="cable pulling Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/cableMachine.png
      # mat by Icongeek26 from <a href="https://thenounproject.com/browse/icons/term/mat/" target="_blank" title="mat Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/yogamat.png
      # Leg Press by Nico Bökenkröger from <a href="https://thenounproject.com/browse/icons/term/leg-press/" target="_blank" title="Leg Press Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/legPressMachine.png
      # yoga ball by Gregor Cresnar from <a href="https://thenounproject.com/browse/icons/term/yoga-ball/" target="_blank" title="yoga ball Icons">Noun Project</a> (CC BY 3.0)
      - assets/equipment/stabilityBall.png

      # ALL MUSCLE GROUP ICONS: From Noun Project by Chris Wilmes (CC BY 3.0)
      - assets/muscleGroups/arms.png
      - assets/muscleGroups/legs_glutesHamstring.png
      - assets/muscleGroups/legs_quads.png
      - assets/muscleGroups/shoulders.png
      - assets/muscleGroups/back.png
      - assets/muscleGroups/chest.png
      - assets/muscleGroups/core.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
