// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCSjQYKfT1ykaF7aeLBTmE_-nInidLWF2M',
      appId: '1:865316383953:web:e302418f06b215c42069f0',
      messagingSenderId: '865316383953',
      projectId: 'workout-96459',
      authDomain: 'workout-96459.firebaseapp.com',
      storageBucket: 'workout-96459.appspot.com',
      measurementId: 'G-7VM8BFE5WB',
      databaseURL: 'https://workout-96459-default-rtdb.firebaseio.com/');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJi2x9F0k31HFzPx2A2kDiqXrjFou5NMI',
    appId: '1:865316383953:android:0936aeccef94cee82069f0',
    messagingSenderId: '865316383953',
    projectId: 'workout-96459',
    storageBucket: 'workout-96459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwki-D_5GefrWMyMwFqY_EMfcf42ls3Ko',
    appId: '1:865316383953:ios:b27db21c14017d612069f0',
    messagingSenderId: '865316383953',
    projectId: 'workout-96459',
    storageBucket: 'workout-96459.appspot.com',
    iosClientId:
        '865316383953-6sccqibcdrt7ps7t6lk6sd9juthakg1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutProgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwki-D_5GefrWMyMwFqY_EMfcf42ls3Ko',
    appId: '1:865316383953:ios:e812a1fc7f04bb112069f0',
    messagingSenderId: '865316383953',
    projectId: 'workout-96459',
    storageBucket: 'workout-96459.appspot.com',
    iosClientId:
        '865316383953-fp1627i878ilrlah7bp0vb6tn9e8tf57.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutProgram.RunnerTests',
  );
}
